[package]
name = "bare-io"
version = "0.1.0"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]
description = "The bare essentials of std::io for use in no_std. No alloc!"
license = "Apache-2.0 OR MIT"
edition = "2018"

[features]
default = ["std"]
std = []